[biophysical_constants]
transcription_saturation_constant=0.036                # units: µM
characteristic_transcript_length=1000                  # units: nt
energy_promoter_state_1=20.0                           # units: kJ/mol
energy_promoter_state_2=-28.8                          # units: kJ/mol
inducer_dissociation_constant=24.19                    # units: muM
inducer_cooperativity_parameter=1.12                   # units: dimensionless
mRNA_half_life_in_min = 11.4345                        # units: min lifetime = 16.5min, half time = 0.693 * 16.5
RNAPII_concentration=0.034                             # units: µM (supplement pdf Table S1 [sigma 70] <35 nM)
transcription_elongation_rate=360                      # units: nt/min 6nt/s * 60s/min (supplement pdf)
transcription_time_constant=0.61                       # units: dimensionless
gene_length_in_nt=690                                  # units: nt (PS pdf)
